[server]
headless = true
enableCORS = false
enableXsrfProtection = false
folderWatchBlacklist = ["transformers", "torch", "sentence_transformers", "chromadb"]

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1a73e8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#202124"
font = "sans serif"

[runner]
magicEnabled = true
